DELETE FROM 
DELETE FROM 
DELETE FROM 
DELETE FROM 
DELETE FROM 

---------- DATOS PAIS ----------

INSERT INTO PAIS		(COD_PAIS,
			NOM_PAIS)
	VALUES(170,
		'COLOMBIA');

---------- DATOS DEPARTAMENTO ----------

INSERT INTO DEPARTAMENTO	(COD_DEP,
				NOM_DEPART,
				COD_PAIS)
	VALUES(5,
		'ANTIOQUIA',
		170);

---------- DATOS CIUDAD ----------

INSERT INTO CIUDAD	(COD_CIUD,
			NOM_CIUD,
			COD_DEPART)
	VALUES(1,
		'GUARNE',
		5);

INSERT INTO CIUDAD	(COD_CIUD,
			NOM_CIUD,
			COD_DEPART)
	VALUES(2,
		'COCORNA',
		5);

INSERT INTO CIUDAD	(COD_CIUD,
			NOM_CIUD,
			COD_DEPART)
	VALUES(3,
		'DON MATIAS',
		5);

INSERT INTO CIUDAD	(COD_CIUD,
			NOM_CIUD,
			COD_DEPART)
	VALUES(4,
		'MEDELLÍN',
		5);

---------- DATOS TIPO DOCUMENTO ----------

INSERT INTO TIPO_DOCUMENTO	(COD_TDOC,
				NOM_TDOC)
	VALUES(1,
		'CEDULA CIUDADANÍA');

INSERT INTO TIPO_DOCUMENTO	(COD_TDOC,
				NOM_TDOC)
	VALUES(2,
		'CEDULA EXTRANJERÍA');

INSERT INTO TIPO_DOCUMENTO	(COD_TDOC,
				NOM_TDOC)
	VALUES(3,
		'CONTRASEÑA');

INSERT INTO TIPO_DOCUMENTO	(COD_TDOC,
				NOM_TDOC)
	VALUES(4,
		'PASAPORTE');

---------- DATOS SANGRE ----------

INSERT INTO SANGRE	(COD_SANGRE,
			TIPO_SANGRE)
	VALUES(1,
		'A');

INSERT INTO SANGRE	(COD_SANGRE,
			TIPO_SANGRE)
	VALUES(2,
		'B');

INSERT INTO SANGRE	(COD_SANGRE,
			TIPO_SANGRE)
	VALUES(3,
		'O');

INSERT INTO SANGRE	(COD_SANGRE,
			TIPO_SANGRE)
	VALUES(4,
		'AB');

---------- DATOS TIPO RH ----------

INSERT INTO RH		(COD_RH,
			NOM_RH)
	VALUES(1,
		'+');

INSERT INTO RH		(COD_RH,
			NOM_RH)
	VALUES(2,
		'-');

---------- DATOS PROFESIONES ----------

INSERT INTO PROFESIONES		(COD_PROF,
				NOM_PROF)
	VALUES(1,
		'VETERINARIO');

INSERT INTO PROFESIONES		(COD_PROF,
				NOM_PROF)
	VALUES(2,
		'ADMINISTRADOR DE EMPRESAS');

INSERT INTO PROFESIONES		(COD_PROF,
				NOM_PROF)
	VALUES(3,
		'ZOOTECNISTA');

---------- DATOS CARGO ----------

INSERT INTO CARGO	(COD_CARG,
			NOM_CARGO)
	VALUES(1,
		'GERENTE');

INSERT INTO CARGO	(COD_CARG,
			NOM_CARGO)
	VALUES(2,
		'MEDICO DE PLANTA');

INSERT INTO CARGO	(COD_CARG,
			NOM_CARGO)
	VALUES(3,
		'AUXILIAR DE MEDICINA');

---------- DATOS TIPO_CONTRATO ----------

INSERT INTO TIPO_CONTRATO	(COD_CONTR,
				NOM_CONTRATO)
	VALUES(1,
		'INDEFINIDO');

INSERT INTO TIPO_CONTRATO	(COD_CONTR,
				NOM_CONTRATO)
	VALUES(3,
		'TERMINO FIJO');

---------- DATOS PERFILES ----------

INSERT INTO PERFILES	(COD_PERF,
			NOM_PERFIL)
	VALUES(1,
		'ADMINISTRADOR');

INSERT INTO PERFILES	(COD_PERF,
			NOM_PERFIL)
	VALUES(2,
		'VETERINARIO');

INSERT INTO PERFILES	(COD_PERF,
			NOM_PERFIL)
	VALUES(3,
		'AUXILIAR');

---------- DATOS USUARIOS ----------

INSERT INTO USUARIOS	(NUM_DOC,
			TIPO_DOC,
			NOMBRES,
			APELLIDO1,
			APELLIDO2,
			FECHA_NAC,
			DEPARTAMENTO,
			CIUDAD,
			TIPO_SANGRE,
			TIPO_RH,
			ESTADO,
			DIRECCION,
			TELEFONO,
			TEL_MOVIL,
			EMAIL,
			PROFESION,
			FECHA_OBT_TITULO,
			CARGO,
			FECHA_CONTRATO,
			TIPO_CONTR)
	VALUES(1111,
		1,
		'JUAN ESTEBAN',
		'ACEVEDO',
		'GALLEGO',
		TO_DATE('1984-02-09','YYYY-MM-DD'),
		5,
		4,
		1,
		1,
		1,
		'CALLE 10',
		555555,
		555555,
		'juan_acevedo23141@elpoli.edu.co',
		NULL,
		TO_DATE('','YYYY-MM-DD'),
		NULL,
		TO_DATE('','YYYY-MM-DD'),
		NULL);

INSERT INTO USUARIOS	(NUM_DOC,
			TIPO_DOC,
			NOMBRES,
			APELLIDO1,
			APELLIDO2,
			FECHA_NAC,
			DEPARTAMENTO,
			CIUDAD,
			TIPO_SANGRE,
			TIPO_RH,
			ESTADO,
			DIRECCION,
			TELEFONO,
			TEL_MOVIL,
			EMAIL,
			PROFESION,
			FECHA_OBT_TITULO,
			CARGO,
			FECHA_CONTRATO,
			TIPO_CONTR)
	VALUES(2222,
		1,
		'IVAN DARIO',
		'VILLA',
		'RAMIREZ',
		TO_DATE('1985-01-15','YYYY-MM-DD'),
		5,
		4,
		1,
		1,
		1,
		'CALLE 10',
		555555,
		555555,
		'trezeguet55@gmail.com',
		NULL,
		TO_DATE('','YYYY-MM-DD'),
		NULL,
		TO_DATE('','YYYY-MM-DD'),
		NULL);

---------- DATOS ASIG_PERFIL ----------

INSERT INTO ASIG_PERFIL	(COD_PERF,
			NUM_DOC,
			TIPO_DOC,
			NOMBRE_APELL,
			PERFIL,
			NOMBRE_USER,
			CONTRASENA)
	VALUES(1,
		1111,
		1,
		'JUAN ESTEBAN ACEVEDO GALLEGO',
		1,
		'jacevedo',
		'Ju@N1984');

INSERT INTO ASIG_PERFIL	(COD_PERF,
			NUM_DOC,
			TIPO_DOC,
			NOMBRE_APELL,
			PERFIL,
			NOMBRE_USER,
			CONTRASENA)
	VALUES(2,
		2222,
		1,
		'IVAN DARIO VILLA RAMIREZ',
		1,
		'ivilla',
		'ivan.85');