DELETE FROM 
DELETE FROM 
DELETE FROM 
DELETE FROM 
DELETE FROM 

---------- DATOS PAIS ----------

INSERT INTO PAIS		(COD_PAIS,
			NOM_PAIS)
	VALUES(170,
		'COLOMBIA');

---------- DATOS DEPARTAMENTO ----------

INSERT INTO DEPARTAMENTO	(COD_DEP,
				NOM_DEPART,
				COD_PAIS)
	VALUES(5,
		'ANTIOQUIA',
		170);

---------- DATOS CIUDAD ----------

INSERT INTO CIUDAD	(COD_CIUD,
			NOM_CIUD,
			COD_DEPART)
	VALUES(1,
		'GUARNE',
		5);

INSERT INTO CIUDAD	(COD_CIUD,
			NOM_CIUD,
			COD_DEPART)
	VALUES(2,
		'COCORNA',
		5);

INSERT INTO CIUDAD	(COD_CIUD,
			NOM_CIUD,
			COD_DEPART)
	VALUES(3,
		'DON MATIAS',
		5);

INSERT INTO CIUDAD	(COD_CIUD,
			NOM_CIUD,
			COD_DEPART)
	VALUES(4,
		'MEDELL�N',
		5);

---------- DATOS TIPO DOCUMENTO ----------

INSERT INTO TIPO_DOCUMENTO	(ID_DOCUM,
				NOM_DOC)
	VALUES(1,
		'CEDULA CIUDADAN�A');

INSERT INTO TIPO_DOCUMENTO	(ID_DOCUM,
				NOM_DOC)
	VALUES(2,
		'CEDULA EXTRANJER�A');

INSERT INTO TIPO_DOCUMENTO	(ID_DOCUM,
				NOM_DOC)
	VALUES(3,
		'CONTRASE�A');

INSERT INTO TIPO_DOCUMENTO	(ID_DOCUM,
				NOM_DOC)
	VALUES(4,
		'PASAPORTE');

---------- DATOS SANGRE ----------

INSERT INTO TIPO_SANGRE	(ID_SANGRE,
			TIPO_SANGRE)
	VALUES(1,
		'A');

INSERT INTO TIPO_SANGRE	(ID_SANGRE,
			TIPO_SANGRE)
	VALUES(2,
		'B');

INSERT INTO TIPO_SANGRE	(ID_SANGRE,
			TIPO_SANGRE)
	VALUES(3,
		'O');

INSERT INTO TIPO_SANGRE	(ID_SANGRE,
			TIPO_SANGRE)
	VALUES(4,
		'AB');

---------- DATOS TIPO RH ----------

INSERT INTO TIPO_RH		(ID_RH,
			NOM_RH)
	VALUES(1,
		'+');

INSERT INTO TIPO_RH		(ID_RH,
			NOM_RH)
	VALUES(2,
		'-');

---------- DATOS PROFESIONES ----------

INSERT INTO PROFESIONES		(ID_PROF,
				NOM_PROF)
	VALUES(1,
		'VETERINARIO');

INSERT INTO PROFESIONES		(ID_PROF,
				NOM_PROF)
	VALUES(2,
		'ADMINISTRADOR DE EMPRESAS');

INSERT INTO PROFESIONES		(ID_PROF,
				NOM_PROF)
	VALUES(3,
		'ZOOTECNISTA');

---------- DATOS CARGOS ----------

INSERT INTO CARGOS	(ID_CARGO,
			NOM_CARGO)
	VALUES(1,
		'GERENTE');

INSERT INTO CARGOS	(ID_CARGO,
			NOM_CARGO)
	VALUES(2,
		'MEDICO DE PLANTA');

INSERT INTO CARGOS	(ID_CARGO,
			NOM_CARGO)
	VALUES(3,
		'AUXILIAR DE MEDICINA');
    
select * from cargos;

---------- DATOS TIPO_CONTRATO ----------

INSERT INTO TIPO_CONTRATO	(ID_TCONT,
				NOM_TCONT)
	VALUES(1,
		'INDEFINIDO');

INSERT INTO TIPO_CONTRATO	(ID_TCONT,
				NOM_TCONT)
	VALUES(3,
		'TERMINO FIJO');

---------- DATOS TIPO_PERFIL ----------

INSERT INTO TIPO_PERFIL	(ID_TPERFIL,
			NOM_TPERFIL)
	VALUES(1,
		'ADMINISTRADOR');

INSERT INTO TIPO_PERFIL	(ID_TPERFIL,
			NOM_TPERFIL)
	VALUES(2,
		'VETERINARIO');

INSERT INTO TIPO_PERFIL	(ID_TPERFIL,
			NOM_TPERFIL)
	VALUES(3,
		'AUXILIAR');

---------- DATOS USUARIOS ----------

INSERT INTO USUARIOS	(NUM_DOC,
			TIPO_DOC,
			NOMBRES,
			APELLIDO1,
			APELLIDO2,
			FECHA_NAC,
			DEPARTAMENTO,
			CIUDAD,
			TIPO_SANGRE,
			TIPO_RH,
			ESTADO,
			DIRECCION,
			TEL_FIJO,
			TEL_MOVIL,
			EMAIL,
			PROFESION,
			FECHA_OBT_TITULO,
			CARGOS,
			FECHA_CONTRATO,
			TIPO_CONTR,
      FOTO,
      OTROS_ESTUDIO,
      TITULO_OBTE,
      FECHA_FINAL)
	VALUES(1111,
		1,
		'JUAN ESTEBAN',
		'ACEVEDO',
		'GALLEGO',
		TO_DATE('1984-02-09','YYYY-MM-DD'),
		5,
		4,
		1,
		1,
		1,
		'CALLE 10',
		555555,
		555555,
		'juan_acevedo23141@elpoli.edu.co',
		1,
		TO_DATE('','YYYY-MM-DD'),
		1,
		TO_DATE('','YYYY-MM-DD'),
		1,
    'ivan',
    'Bateriologo',
    'si',
    TO_DATE('2010/05/02','YYYY-MM-DD'));

INSERT INTO USUARIOS	(NUM_DOC,
			TIPO_DOC,
			NOMBRES,
			APELLIDO1,
			APELLIDO2,
			FECHA_NAC,
			DEPARTAMENTO,
			CIUDAD,
			TIPO_SANGRE,
			TIPO_RH,
			ESTADO,
			DIRECCION,
			TEL_FIJO,
			TEL_MOVIL,
			EMAIL,
			PROFESION,
			FECHA_OBT_TITULO,
			CARGO,
			FECHA_CONTRATO,
			TIPO_CONTR,
      FOTO,
      OTROS_ESTUDIO,
      TITULO_OBTE,
      FECHA_FINAL)
	VALUES(2222,
		1,
		'IVAN DARIO',
		'VILLA',
		'RAMIREZ',
		TO_DATE('1985-01-15','YYYY-MM-DD'),
		5,
		4,
		1,
		1,
		1,
		'CALLE 10',
		555555,
		555555,
		'trezeguet55@gmail.com',
		2,
		TO_DATE('2012/05/03','YYYY-MM-DD'),
		1,
		TO_DATE('2014/10/20','YYYY-MM-DD'),
		1,
    'ivan',
    'Bateriologo',
    'si',
    TO_DATE('2010/05/02','YYYY-MM-DD'));
    
select * from usuarios where num_doc = 2222;

---------- DATOS ASIG_PERFIL ----------

INSERT INTO PERFILES	(ID_PERFIL,
      NOM_USUARIO,
			CLAVE,
			TPERFIL,			
			NUM_DOC_USU)
	VALUES(1,
		'Ivan',
		'Ivan.1585',
    1,
    8359459);
    
    select * from PERFILES where NOM_USUARIO='Ivan' and CLAVE='Ivan.1585';

INSERT INTO ASIG_PERFIL	(ID_TPERFIL,
			NUM_DOC,
			TIPO_DOC,
			NOMBRE_APELL,
			PERFIL,
			NOMBRE_USER,
			CONTRASENA)
	VALUES(2,
		2222,
		1,
		'IVAN DARIO VILLA RAMIREZ',
		1,
		'ivilla',
		'ivan.85');