--------  PRIMARIAS  --------

ALTER TABLE USUARIOS
	ADD CONSTRAINT PK_DOCUMENTO PRIMARY KEY (NUM_DOC, TIPO_DOC);

ALTER TABLE ASIG_PERFIL
	ADD CONSTRAINT PK_COD_PERFIL PRIMARY KEY (COD_PERF);


ALTER TABLE PERFILES
	ADD CONSTRAINT PK_COD_REGIST PRIMARY KEY (COD_PERF);

ALTER TABLE PAIS
	ADD CONSTRAINT PK_COD_PAIS PRIMARY KEY (COD_PAIS);

ALTER TABLE DEPARTAMENTO
	ADD CONSTRAINT PK_COD_DEPART PRIMARY KEY (COD_DEP);

ALTER TABLE CIUDAD
	ADD CONSTRAINT PK_COD_CIUD PRIMARY KEY (COD_CIUD);

ALTER TABLE TIPO_DOCUMENTO
	ADD CONSTRAINT PK_COD_TIPODOC PRIMARY KEY (COD_TDOC);

ALTER TABLE SANGRE
	ADD CONSTRAINT PK_COD_SANGRE PRIMARY KEY (COD_SANGRE);

ALTER TABLE RH
	ADD CONSTRAINT PK_COD_RH PRIMARY KEY (COD_RH);

ALTER TABLE PROFESIONES
	ADD CONSTRAINT PK_COD_PROF PRIMARY KEY (COD_PROF);

ALTER TABLE CARGO
	ADD CONSTRAINT PK_COD_CARGO PRIMARY KEY (COD_CARG);

ALTER TABLE TIPO_CONTRATO
	ADD CONSTRAINT PK_COD_CONTR PRIMARY KEY (COD_CONTR);


--------  FORANEAS  --------


ALTER TABLE DEPARTAMENTO
	ADD CONSTRAINT FK_CODPAIS FOREIGN KEY (COD_PAIS)
	REFERENCES PAIS (COD_PAIS);

ALTER TABLE CIUDAD
	ADD CONSTRAINT FK_CODDEPART FOREIGN KEY (COD_DEPART)
	REFERENCES DEPARTAMENTO (COD_DEP);

ALTER TABLE USUARIOS
	ADD CONSTRAINT FK_TIPO_DOC FOREIGN KEY (TIPO_DOC)
	REFERENCES TIPO_DOCUMENTO (COD_TDOC);

ALTER TABLE USUARIOS
	ADD CONSTRAINT FK_DEPART FOREIGN KEY (DEPARTAMENTO)
	REFERENCES DEPARTAMENTO (COD_DEP);

ALTER TABLE USUARIOS
	ADD CONSTRAINT FK_CIUDAD FOREIGN KEY (CIUDAD)
	REFERENCES CIUDAD (COD_CIUD);

ALTER TABLE USUARIOS
	ADD CONSTRAINT FK_TIPO_SANGRE FOREIGN KEY (TIPO_SANGRE)
	REFERENCES SANGRE (COD_SANGRE);

ALTER TABLE USUARIOS
	ADD CONSTRAINT FK_TIPO_RH FOREIGN KEY (TIPO_RH)
	REFERENCES RH (COD_RH);

ALTER TABLE USUARIOS
	ADD CONSTRAINT FK_PROFESION FOREIGN KEY (PROFESION)
	REFERENCES PROFESIONES (COD_PROF);

ALTER TABLE USUARIOS
	ADD CONSTRAINT FK_CARGO FOREIGN KEY (CARGO)
	REFERENCES CARGO (COD_CARG);

ALTER TABLE USUARIOS
	ADD CONSTRAINT FK_TCONTRATO FOREIGN KEY (TIPO_CONTR)
	REFERENCES TIPO_CONTRATO (COD_CONTR);

ALTER TABLE ASIG_PERFIL
	ADD CONSTRAINT FK_TDOC FOREIGN KEY (TIPO_DOC)
	REFERENCES TIPO_DOCUMENTO (COD_TDOC);

ALTER TABLE ASIG_PERFIL
	ADD CONSTRAINT FK_PERFIL FOREIGN KEY (PERFIL)
	REFERENCES PERFILES (COD_PERF);

------- CHEQUEOS -----------



ALTER TABLE USUARIOS
	ADD CONSTRAINT NN_NUM_DOC CHECK (NUM_DOC IS NOT NULL);

ALTER TABLE USUARIOS
	ADD CONSTRAINT NN_TIPO_DOC CHECK (TIPO_DOC IS NOT NULL);

ALTER TABLE USUARIOS
	ADD CONSTRAINT NN_NOMBRES CHECK (NOMBRES IS NOT NULL);

ALTER TABLE USUARIOS
	ADD CONSTRAINT NN_APELLIDO1 CHECK (APELLIDO1 IS NOT NULL);

ALTER TABLE USUARIOS
	ADD CONSTRAINT NN_FECHA_NAC CHECK (FECHA_NAC IS NOT NULL);

ALTER TABLE USUARIOS
	ADD CONSTRAINT NN_ESTADO CHECK (ESTADO IS NOT NULL);

ALTER TABLE USUARIOS
	ADD CONSTRAINT NN_DIRECCION CHECK (DIRECCION IS NOT NULL);

ALTER TABLE USUARIOS
	ADD CONSTRAINT NN_TELEFONO CHECK (TELEFONO IS NOT NULL);

ALTER TABLE USUARIOS
	ADD CONSTRAINT NN_TEL_MOVIL CHECK (TEL_MOVIL IS NOT NULL);

ALTER TABLE USUARIOS
	ADD CONSTRAINT NN_EMAIL CHECK (EMAIL IS NOT NULL);

ALTER TABLE ASIG_PERFIL
	ADD CONSTRAINT NN_NUMDOCU CHECK (NUM_DOC IS NOT NULL);

ALTER TABLE ASIG_PERFIL
	ADD CONSTRAINT NN_PERFIL CHECK (PERFIL IS NOT NULL);

ALTER TABLE ASIG_PERFIL
	ADD CONSTRAINT NN_NOM_USU CHECK (NOMBRE_USER IS NOT NULL);

ALTER TABLE ASIG_PERFIL
	ADD CONSTRAINT NN_CONTRASENA CHECK (CONTRASENA IS NOT NULL);

ALTER TABLE PERFILES
	ADD CONSTRAINT NN_NOMPERFIL CHECK (NOM_PERFIL IS NOT NULL);

ALTER TABLE PAIS
	ADD CONSTRAINT NN_NOM_PAIS CHECK (NOM_PAIS IS NOT NULL);

ALTER TABLE DEPARTAMENTO
	ADD CONSTRAINT NN_NOM_DEPART CHECK (NOM_DEPART IS NOT NULL);

ALTER TABLE DEPARTAMENTO
	ADD CONSTRAINT NN_COD_PAIS CHECK (COD_PAIS IS NOT NULL);

ALTER TABLE CIUDAD
	ADD CONSTRAINT NN_NOM_CIUD CHECK (NOM_CIUD IS NOT NULL);

ALTER TABLE CIUDAD
	ADD CONSTRAINT NN_COD_DEPART CHECK (COD_DEPART IS NOT NULL);

ALTER TABLE TIPO_DOCUMENTO
	ADD CONSTRAINT NN_NOM_TDOC CHECK (NOM_TDOC IS NOT NULL);

ALTER TABLE SANGRE
	ADD CONSTRAINT NN_TIPO_SANGRE CHECK (TIPO_SANGRE IS NOT NULL);

ALTER TABLE RH
	ADD CONSTRAINT NN_NOM_RH CHECK (NOM_RH IS NOT NULL);

ALTER TABLE PROFESIONES
	ADD CONSTRAINT NN_NOM_PROF CHECK (NOM_PROF IS NOT NULL);

ALTER TABLE CARGO
	ADD CONSTRAINT NN_NOM_CARGO CHECK (NOM_CARGO IS NOT NULL);

ALTER TABLE TIPO_CONTRATO
	ADD CONSTRAINT NN_NOM_CONTRATO CHECK (NOM_CONTRATO IS NOT NULL);
